use std::fmt;

/// Database dialect enum for handling database-specific SQL generation and features
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DatabaseDialect {
    /// SQLite database dialect (always available)
    SQLite,
    
    /// PostgreSQL database dialect (requires "postgres" feature)
    #[cfg(feature = "postgres")]
    PostgreSQL,
    
    /// MySQL database dialect (requires "mysql" feature)
    #[cfg(feature = "mysql")]
    MySQL,
}

impl fmt::Display for DatabaseDialect {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            DatabaseDialect::SQLite => write!(f, "SQLite"),
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => write!(f, "PostgreSQL"),
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => write!(f, "MySQL"),
        }
    }
}

impl DatabaseDialect {
    /// Check if the database supports RETURNING clauses
    /// 
    /// SQLite and PostgreSQL support RETURNING, MySQL does not
    pub fn supports_returning(&self) -> bool {
        match self {
            DatabaseDialect::SQLite => true,
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => true,
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => false,
        }
    }
    
    /// Quote an identifier according to database-specific rules
    /// 
    /// Each database has different identifier quoting conventions:
    /// - SQLite: backticks `identifier`
    /// - PostgreSQL: double quotes "identifier"
    /// - MySQL: backticks `identifier`
    pub fn quote_identifier(&self, name: &str) -> String {
        match self {
            DatabaseDialect::SQLite => format!("`{}`", name),
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => format!("\"{}\"", name),
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => format!("`{}`", name),
        }
    }
    
    /// Check if the database supports ON CONFLICT clauses (UPSERT)
    /// 
    /// SQLite and PostgreSQL support ON CONFLICT, MySQL uses ON DUPLICATE KEY UPDATE
    pub fn supports_on_conflict(&self) -> bool {
        match self {
            DatabaseDialect::SQLite => true,
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => true,
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => false,
        }
    }
    
    /// Check if the database supports CTEs (Common Table Expressions)
    /// 
    /// All modern versions of these databases support CTEs
    pub fn supports_cte(&self) -> bool {
        match self {
            DatabaseDialect::SQLite => true,
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => true,
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => true,
        }
    }
    
    /// Check if the database supports window functions
    /// 
    /// All supported databases have window function support
    pub fn supports_window_functions(&self) -> bool {
        match self {
            DatabaseDialect::SQLite => true,
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => true,
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => true,
        }
    }
    
    /// Get the database-specific boolean representation
    /// 
    /// Different databases handle booleans differently:
    /// - SQLite: INTEGER (0/1)
    /// - PostgreSQL: BOOLEAN
    /// - MySQL: BOOLEAN (alias for TINYINT(1))
    pub fn boolean_type(&self) -> &'static str {
        match self {
            DatabaseDialect::SQLite => "INTEGER",
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => "BOOLEAN",
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => "BOOLEAN",
        }
    }
    
    /// Get the database-specific auto-increment syntax
    /// 
    /// Each database has different auto-increment syntax:
    /// - SQLite: AUTOINCREMENT
    /// - PostgreSQL: SERIAL/BIGSERIAL or GENERATED BY DEFAULT AS IDENTITY
    /// - MySQL: AUTO_INCREMENT
    pub fn auto_increment_keyword(&self) -> &'static str {
        match self {
            DatabaseDialect::SQLite => "AUTOINCREMENT",
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => "SERIAL",
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => "AUTO_INCREMENT",
        }
    }
    
    /// Get the limit/offset syntax preferences
    /// 
    /// All databases support LIMIT/OFFSET, but MySQL historically used LIMIT offset, count
    pub fn prefers_limit_offset(&self) -> bool {
        match self {
            DatabaseDialect::SQLite => true,
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => true,
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => true, // Modern MySQL supports LIMIT/OFFSET
        }
    }
    
    /// Check if the database requires explicit casting for certain operations
    /// 
    /// PostgreSQL is stricter about type casting than SQLite/MySQL
    pub fn requires_explicit_casting(&self) -> bool {
        match self {
            DatabaseDialect::SQLite => false,
            #[cfg(feature = "postgres")]
            DatabaseDialect::PostgreSQL => true,
            #[cfg(feature = "mysql")]
            DatabaseDialect::MySQL => false,
        }
    }
    
    /// Get all available dialects (useful for testing across all backends)
    /// 
    /// Returns a vector of all dialects that are compiled in based on feature flags
    pub fn all_available() -> Vec<Self> {
        #[cfg(any(feature = "postgres", feature = "mysql"))]
        let mut dialects = vec![DatabaseDialect::SQLite];
        
        #[cfg(not(any(feature = "postgres", feature = "mysql")))]
        let dialects = vec![DatabaseDialect::SQLite];
        
        #[cfg(feature = "postgres")]
        dialects.push(DatabaseDialect::PostgreSQL);
        
        #[cfg(feature = "mysql")]
        dialects.push(DatabaseDialect::MySQL);
        
        dialects
    }
    
    /// Parse dialect from string (case-insensitive)
    /// 
    /// Useful for configuration parsing
    pub fn from_str(s: &str) -> Result<Self, String> {
        match s.to_lowercase().as_str() {
            "sqlite" | "sqlite3" => Ok(DatabaseDialect::SQLite),
            #[cfg(feature = "postgres")]
            "postgres" | "postgresql" | "pg" => Ok(DatabaseDialect::PostgreSQL),
            #[cfg(feature = "mysql")]
            "mysql" | "mariadb" => Ok(DatabaseDialect::MySQL),
            _ => {
                let available: Vec<String> = Self::all_available()
                    .iter()
                    .map(|d| d.to_string().to_lowercase())
                    .collect();
                Err(format!(
                    "Unknown database dialect '{}'. Available: {}",
                    s,
                    available.join(", ")
                ))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_database_dialect_display() {
        assert_eq!(DatabaseDialect::SQLite.to_string(), "SQLite");
        
        #[cfg(feature = "postgres")]
        assert_eq!(DatabaseDialect::PostgreSQL.to_string(), "PostgreSQL");
        
        #[cfg(feature = "mysql")]
        assert_eq!(DatabaseDialect::MySQL.to_string(), "MySQL");
    }
    
    #[test]
    fn test_supports_returning() {
        assert_eq!(DatabaseDialect::SQLite.supports_returning(), true);
        
        #[cfg(feature = "postgres")]
        assert_eq!(DatabaseDialect::PostgreSQL.supports_returning(), true);
        
        #[cfg(feature = "mysql")]
        assert_eq!(DatabaseDialect::MySQL.supports_returning(), false);
    }
    
    #[test]
    fn test_quote_identifier() {
        assert_eq!(DatabaseDialect::SQLite.quote_identifier("table"), "`table`");
        assert_eq!(DatabaseDialect::SQLite.quote_identifier("column_name"), "`column_name`");
        
        #[cfg(feature = "postgres")]
        {
            assert_eq!(DatabaseDialect::PostgreSQL.quote_identifier("table"), "\"table\"");
            assert_eq!(DatabaseDialect::PostgreSQL.quote_identifier("column_name"), "\"column_name\"");
        }
        
        #[cfg(feature = "mysql")]
        {
            assert_eq!(DatabaseDialect::MySQL.quote_identifier("table"), "`table`");
            assert_eq!(DatabaseDialect::MySQL.quote_identifier("column_name"), "`column_name`");
        }
    }
    
    #[test]
    fn test_supports_on_conflict() {
        assert_eq!(DatabaseDialect::SQLite.supports_on_conflict(), true);
        
        #[cfg(feature = "postgres")]
        assert_eq!(DatabaseDialect::PostgreSQL.supports_on_conflict(), true);
        
        #[cfg(feature = "mysql")]
        assert_eq!(DatabaseDialect::MySQL.supports_on_conflict(), false);
    }
    
    #[test]
    fn test_boolean_type() {
        assert_eq!(DatabaseDialect::SQLite.boolean_type(), "INTEGER");
        
        #[cfg(feature = "postgres")]
        assert_eq!(DatabaseDialect::PostgreSQL.boolean_type(), "BOOLEAN");
        
        #[cfg(feature = "mysql")]
        assert_eq!(DatabaseDialect::MySQL.boolean_type(), "BOOLEAN");
    }
    
    #[test]
    fn test_auto_increment_keyword() {
        assert_eq!(DatabaseDialect::SQLite.auto_increment_keyword(), "AUTOINCREMENT");
        
        #[cfg(feature = "postgres")]
        assert_eq!(DatabaseDialect::PostgreSQL.auto_increment_keyword(), "SERIAL");
        
        #[cfg(feature = "mysql")]
        assert_eq!(DatabaseDialect::MySQL.auto_increment_keyword(), "AUTO_INCREMENT");
    }
    
    #[test]
    fn test_feature_support_methods() {
        // Test that all dialects support common features
        for dialect in DatabaseDialect::all_available() {
            assert!(dialect.supports_cte(), "All dialects should support CTEs");
            assert!(dialect.supports_window_functions(), "All dialects should support window functions");
            assert!(dialect.prefers_limit_offset(), "All modern versions should support LIMIT/OFFSET");
        }
        
        // Test PostgreSQL-specific strictness
        #[cfg(feature = "postgres")]
        assert!(DatabaseDialect::PostgreSQL.requires_explicit_casting());
        
        // Test SQLite/MySQL are more permissive
        assert!(!DatabaseDialect::SQLite.requires_explicit_casting());
        
        #[cfg(feature = "mysql")]
        assert!(!DatabaseDialect::MySQL.requires_explicit_casting());
    }
    
    #[test]
    fn test_all_available() {
        let available = DatabaseDialect::all_available();
        
        // SQLite should always be available
        assert!(available.contains(&DatabaseDialect::SQLite));
        
        // Test that the count matches expectations based on features
        #[cfg(all(feature = "postgres", feature = "mysql"))]
        assert_eq!(available.len(), 3);
        
        #[cfg(all(feature = "postgres", not(feature = "mysql")))]
        assert_eq!(available.len(), 2);
        
        #[cfg(all(not(feature = "postgres"), feature = "mysql"))]
        assert_eq!(available.len(), 2);
        
        #[cfg(all(not(feature = "postgres"), not(feature = "mysql")))]
        assert_eq!(available.len(), 1);
    }
    
    #[test]
    fn test_from_str() {
        // Test successful parsing
        assert_eq!(DatabaseDialect::from_str("sqlite").unwrap(), DatabaseDialect::SQLite);
        assert_eq!(DatabaseDialect::from_str("SQLITE").unwrap(), DatabaseDialect::SQLite);
        assert_eq!(DatabaseDialect::from_str("sqlite3").unwrap(), DatabaseDialect::SQLite);
        
        #[cfg(feature = "postgres")]
        {
            assert_eq!(DatabaseDialect::from_str("postgres").unwrap(), DatabaseDialect::PostgreSQL);
            assert_eq!(DatabaseDialect::from_str("postgresql").unwrap(), DatabaseDialect::PostgreSQL);
            assert_eq!(DatabaseDialect::from_str("PG").unwrap(), DatabaseDialect::PostgreSQL);
        }
        
        #[cfg(feature = "mysql")]
        {
            assert_eq!(DatabaseDialect::from_str("mysql").unwrap(), DatabaseDialect::MySQL);
            assert_eq!(DatabaseDialect::from_str("MYSQL").unwrap(), DatabaseDialect::MySQL);
            assert_eq!(DatabaseDialect::from_str("mariadb").unwrap(), DatabaseDialect::MySQL);
        }
        
        // Test error cases
        let result = DatabaseDialect::from_str("unknown");
        assert!(result.is_err());
        let error_msg = result.unwrap_err();
        assert!(error_msg.contains("Unknown database dialect"));
        assert!(error_msg.contains("Available:"));
    }
    
    #[test]
    fn test_dialect_equality_and_hash() {
        use std::collections::HashSet;
        
        let mut set = HashSet::new();
        set.insert(DatabaseDialect::SQLite);
        
        // Test that same dialects are equal and hashable
        assert!(set.contains(&DatabaseDialect::SQLite));
        
        #[cfg(feature = "postgres")]
        {
            set.insert(DatabaseDialect::PostgreSQL);
            assert!(set.contains(&DatabaseDialect::PostgreSQL));
            assert_ne!(DatabaseDialect::SQLite, DatabaseDialect::PostgreSQL);
        }
        
        #[cfg(feature = "mysql")]
        {
            set.insert(DatabaseDialect::MySQL);
            assert!(set.contains(&DatabaseDialect::MySQL));
            assert_ne!(DatabaseDialect::SQLite, DatabaseDialect::MySQL);
        }
    }
    
    #[test]
    fn test_clone_and_copy() {
        let dialect = DatabaseDialect::SQLite;
        let cloned = dialect.clone();
        let copied = dialect;
        
        assert_eq!(dialect, cloned);
        assert_eq!(dialect, copied);
    }
    
    #[test]
    fn test_debug_format() {
        let debug_str = format!("{:?}", DatabaseDialect::SQLite);
        assert_eq!(debug_str, "SQLite");
        
        #[cfg(feature = "postgres")]
        {
            let debug_str = format!("{:?}", DatabaseDialect::PostgreSQL);
            assert_eq!(debug_str, "PostgreSQL");
        }
        
        #[cfg(feature = "mysql")]
        {
            let debug_str = format!("{:?}", DatabaseDialect::MySQL);
            assert_eq!(debug_str, "MySQL");
        }
    }
}