pub use d1orm_derive::*;

pub mod db;
pub mod query;
pub mod entity;
pub mod migrations;
pub mod types;
pub mod schema;

pub use db::*;
pub use query::*;
pub use entity::*;
pub use migrations::*;
pub use types::*;
pub use schema::*;

pub use async_trait::async_trait;
use std::fmt;

#[cfg(target_arch = "wasm32")]
use worker::d1::D1Database;

#[derive(Debug)]
pub enum D1OrmError {
    Database(String),
    NotFound,
    ValidationError(String),
    SerializationError(String),
}

impl fmt::Display for D1OrmError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            D1OrmError::Database(msg) => write!(f, "Database error: {}", msg),
            D1OrmError::NotFound => write!(f, "Entity not found"),
            D1OrmError::ValidationError(msg) => write!(f, "Validation error: {}", msg),
            D1OrmError::SerializationError(msg) => write!(f, "Serialization error: {}", msg),
        }
    }
}

impl std::error::Error for D1OrmError {}

pub type Result<T> = std::result::Result<T, D1OrmError>;

pub trait Entity: Sized + serde::Serialize + serde::de::DeserializeOwned {
    type PrimaryKey: Clone + fmt::Debug + serde::Serialize + serde::de::DeserializeOwned;
    type QueryBuilder: QueryBuilder<Self>;
    type CreateBuilder: CreateBuilder<Self>;
    type UpdateBuilder: UpdateBuilder<Self>;

    const TABLE_NAME: &'static str;
    
    fn primary_key(&self) -> &Self::PrimaryKey;
    
    fn query() -> Self::QueryBuilder;
    fn create() -> Self::CreateBuilder;
    fn update(key: Self::PrimaryKey) -> Self::UpdateBuilder;
    
    /// Returns field names that are boolean types - generated by derive macro
    fn boolean_fields() -> &'static [&'static str];
    
    /// Convert boolean fields from SQLite integers to Rust booleans
    fn convert_from_sqlite(mut value: serde_json::Value) -> serde_json::Value {
        if let serde_json::Value::Object(ref mut map) = value {
            for field_name in Self::boolean_fields() {
                if let Some(serde_json::Value::Number(n)) = map.get(*field_name) {
                    if let Some(i) = n.as_i64() {
                        if i == 0 || i == 1 {
                            map.insert(field_name.to_string(), serde_json::Value::Bool(i != 0));
                        }
                    }
                }
            }
            
            // Also handle SQLite datetime strings -> RFC3339 format for DateTime<Utc>
            for (field_name, field_value) in map.iter_mut() {
                if let serde_json::Value::String(date_str) = field_value {
                    if field_name.ends_with("_at") || field_name.contains("time") {
                        // Try to parse and reformat SQLite datetime to RFC3339
                        if let Ok(naive_dt) = chrono::NaiveDateTime::parse_from_str(date_str, "%Y-%m-%d %H:%M:%S") {
                            let utc_dt = naive_dt.and_utc();
                            *field_value = serde_json::Value::String(utc_dt.to_rfc3339());
                        }
                    }
                }
            }
        }
        value
    }
    
    /// Convert boolean fields from Rust booleans to SQLite integers
    fn convert_to_sqlite(mut value: serde_json::Value) -> serde_json::Value {
        if let serde_json::Value::Object(ref mut map) = value {
            for field_name in Self::boolean_fields() {
                if let Some(serde_json::Value::Bool(b)) = map.get(*field_name) {
                    map.insert(field_name.to_string(), serde_json::Value::Number((*b as i64).into()));
                }
            }
        }
        value
    }
    
    async fn find(db: &D1Client, key: Self::PrimaryKey) -> Result<Option<Self>>;
    async fn delete(db: &D1Client, key: Self::PrimaryKey) -> Result<()>;
}

pub trait QueryBuilder<T: Entity> {
    async fn all(self, db: &D1Client) -> Result<Vec<T>>;
    async fn first(self, db: &D1Client) -> Result<Option<T>>;
    async fn count(self, db: &D1Client) -> Result<i64>;
}

pub trait CreateBuilder<T: Entity> {
    async fn save(self, db: &D1Client) -> Result<T>;
}

pub trait UpdateBuilder<T: Entity> {
    async fn save(self, db: &D1Client) -> Result<T>;
}